import { Platform } from "react-native";

const NAVY = "#0F172A";
const NAVY_MUTED = "#1E293B";

export const Colors = {
  light: {
    text: NAVY,
    background: "#FFFFFF",
    card: "#FFFFFF",
    border: "#E2E8F0",
    backgroundElement: "#F8FAFC",
    backgroundSelected: "#E2E8F0",
    textSecondary: "#64748B",
    textMuted: "#94A3B8",
    primary: NAVY,
    primaryMuted: "#F1F5F9",
    accent: NAVY_MUTED,
    onPrimary: "#FFFFFF",
    error: "#DC2626",
    shellBackground: "#FFFFFF",
    headerGradientStart: "#FFFFFF",
    headerGradientEnd: "#FFFFFF",
    headerBorder: "#F1F5F9",
    statusBarStyle: "dark-content" as const,
    fabBackground: NAVY,
    fabIcon: "#FFFFFF",
    calendarSelected: NAVY,
    calendarSelectedText: "#FFFFFF",
    periodBadgeBg: "#F1F5F9",
    periodBadgeText: NAVY,
    emptyBorder: "#CBD5E1",
    emptyBackground: "#F8FAFC",
    emptyText: "#94A3B8",
    notificationBannerBg: "#F8FAFC",
    notificationBannerBorder: "#E2E8F0",
    success: "#16A34A",
    warning: "#D97706",
    danger: "#DC2626",
    onDanger: "#FFFFFF",
    buttonDisabled: "#CBD5E1",
    onButtonDisabled: "#475569",
    shadow: NAVY,
  },
  dark: {
    text: "#F8FAFC",
    background: "#0F172A",
    card: "#1E293B",
    border: "#334155",
    backgroundElement: "#1E293B",
    backgroundSelected: "#334155",
    textSecondary: "#94A3B8",
    textMuted: "#64748B",
    primary: "#F8FAFC",
    primaryMuted: "#1E293B",
    accent: "#CBD5E1",
    onPrimary: "#0F172A",
    error: "#F87171",
    shellBackground: "#0F172A",
    headerGradientStart: "#0F172A",
    headerGradientEnd: "#0F172A",
    headerBorder: "#1E293B",
    statusBarStyle: "light-content" as const,
    fabBackground: "#F8FAFC",
    fabIcon: "#0F172A",
    calendarSelected: "#F8FAFC",
    calendarSelectedText: "#0F172A",
    periodBadgeBg: "#1E293B",
    periodBadgeText: "#F8FAFC",
    emptyBorder: "#334155",
    emptyBackground: "#1E293B",
    emptyText: "#64748B",
    notificationBannerBg: "#1E293B",
    notificationBannerBorder: "#334155",
    success: "#4ADE80",
    warning: "#FBBF24",
    danger: "#F87171",
    // Vermelho claro no escuro: texto escuro é o que tem contraste em cima dele.
    onDanger: NAVY,
    buttonDisabled: "#334155",
    onButtonDisabled: "#94A3B8",
    shadow: "#000000",
  },
} as const;

export type ThemeColor = keyof typeof Colors.light & keyof typeof Colors.dark;

export const Fonts = Platform.select({
  ios: {
    sans: "PlusJakartaSans_400Regular",
    medium: "PlusJakartaSans_500Medium",
    semiBold: "PlusJakartaSans_600SemiBold",
    bold: "PlusJakartaSans_700Bold",
    extraBold: "PlusJakartaSans_800ExtraBold",
  },
  default: {
    sans: "PlusJakartaSans_400Regular",
    medium: "PlusJakartaSans_500Medium",
    semiBold: "PlusJakartaSans_600SemiBold",
    bold: "PlusJakartaSans_700Bold",
    extraBold: "PlusJakartaSans_800ExtraBold",
  },
  web: {
    sans: "Plus Jakarta Sans",
    medium: "Plus Jakarta Sans",
    semiBold: "Plus Jakarta Sans",
    bold: "Plus Jakarta Sans",
    extraBold: "Plus Jakarta Sans",
  },
});

export const Spacing = {
  half: 2,
  one: 4,
  two: 8,
  three: 16,
  four: 24,
  five: 32,
  six: 64,
} as const;
